[tool.poetry]
name = "pcdc-aws-client"
version = "0.0.1"
description = "aws client"
authors = ["Paul Murdoch <t-9murdo@uchicago.edu>"]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.24.14"
cdiserrors = "^1.0.0"
pytest = "^7.1.2"
cdispyutils = "^2.0.0"
retry = "^0.9.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
