[tool.poetry]
name = "aws_client"
version = "0.1.0"
description = "aws client"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.7"
boto3 = "^1.24.17"
cdiserrors = "^1.0.0"
cdispyutils = "^2.0.0"
retry = "^0.9.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
