import pytest
from unittest.mock import patch, MagicMock
from pcdc_aws_client.errors import InternalError
from botocore.exceptions import ClientError


def test_config_sets_client(boto_manager):
    bm, _ = boto_manager
    with patch("pcdc_aws_client.boto.client") as mock_client:
            new_client = MagicMock()
            mock_client.return_value = new_client
            config = {"aws_access_key_id": "AKDAW", "aws_secret_access_key": "ssdfsl"}
            bm.send_email("a@example.com", "b@example.com", "Hi", "<p>hi</p>", config=config)
            mock_client.assert_called_once_with("ses", **config)
            new_client.send_email.assert_called_once()

def make_client_error(message="Message rejected"):
    return ClientError(
        error_response={"Error": {"Code": "MessageRejected", "Message": message}},
        operation_name="SendEmail",
    )


def test_recipient_string_is_wrapped_in_list(boto_manager):
    bm, _ = boto_manager
    ses_client = bm.ses_client
    ses_client.send_email.return_value = {"MessageId": "abc123"}

    bm.send_email(
        SENDER="a@example.com",
        RECIPIENT="b@example.com",
        SUBJECT="Hi",
        BODY_HTML="<p>hello</p>",
    )

    _, kwargs = ses_client.send_email.call_args
    assert kwargs["Destination"]["ToAddresses"] == ["b@example.com"]


def test_recipient_list_is_passed_through_unchanged(boto_manager):
    bm, _ = boto_manager
    ses_client = bm.ses_client
    ses_client.send_email.return_value = {"MessageId": "abc123"}

    recipients = ["b@example.com", "c@example.com"]
    bm.send_email(
        SENDER="a@example.com", RECIPIENT=recipients, SUBJECT="Hi", BODY_HTML="<p>hi</p>"
    )

    _, kwargs = ses_client.send_email.call_args
    assert kwargs["Destination"]["ToAddresses"] == recipients
    assert kwargs["Destination"]["ToAddresses"] is recipients  # not copied/rebuilt


def test_cc_recipients_defaults_to_empty_list_when_none(boto_manager):
    bm, _ = boto_manager
    ses_client = bm.ses_client
    ses_client.send_email.return_value = {"MessageId": "abc123"}

    bm.send_email(SENDER="a@example.com", RECIPIENT="b@example.com", SUBJECT="Hi", BODY_HTML="<p>hi</p>")

    _, kwargs = ses_client.send_email.call_args
    assert kwargs["Destination"]["CcAddresses"] == []


def test_cc_recipients_string_is_wrapped_in_list(boto_manager):
    bm, _ = boto_manager
    ses_client = bm.ses_client
    ses_client.send_email.return_value = {"MessageId": "abc123"}

    bm.send_email(
        SENDER="a@example.com", RECIPIENT="b@example.com", SUBJECT="Hi",
        BODY_HTML="<p>hi</p>", CC_RECIPIENTS="cc@example.com",
    )

    _, kwargs = ses_client.send_email.call_args
    assert kwargs["Destination"]["CcAddresses"] == ["cc@example.com"]


def test_cc_recipients_list_is_passed_through_unchanged(boto_manager):
    bm, _ = boto_manager
    ses_client = bm.ses_client
    ses_client.send_email.return_value = {"MessageId": "abc123"}

    cc_list = ["cc1@example.com", "cc2@example.com"]
    bm.send_email(
        SENDER="a@example.com", RECIPIENT="b@example.com", SUBJECT="Hi",
        BODY_HTML="<p>hi</p>", CC_RECIPIENTS=cc_list,
    )

    _, kwargs = ses_client.send_email.call_args
    assert kwargs["Destination"]["CcAddresses"] == cc_list


def test_body_text_autogenerated_when_not_provided(boto_manager):
    bm, _ = boto_manager
    ses_client = bm.ses_client
    ses_client.send_email.return_value = {"MessageId": "abc123"}

    with patch("pcdc_aws_client.boto.html2text") as mock_html2text:
        mock_html2text.html2text.return_value = "hello (plain text)"

        bm.send_email(
            SENDER="a@example.com", RECIPIENT="b@example.com", SUBJECT="Hi",
            BODY_HTML="<p>hello</p>",
        )

        mock_html2text.html2text.assert_called_once_with("<p>hello</p>")

    _, kwargs = ses_client.send_email.call_args
    assert kwargs["Message"]["Body"]["Text"]["Data"] == "hello (plain text)"


def test_body_text_not_overwritten_when_explicitly_provided(boto_manager):
    bm, _ = boto_manager
    ses_client = bm.ses_client
    ses_client.send_email.return_value = {"MessageId": "abc123"}

    with patch("pcdc_aws_client.boto.html2text") as mock_html2text:
        bm.send_email(
            SENDER="a@example.com", RECIPIENT="b@example.com", SUBJECT="Hi",
            BODY_HTML="<p>hello</p>", BODY_TEXT="plain hello",
        )

        mock_html2text.html2text.assert_not_called()

    _, kwargs = ses_client.send_email.call_args
    assert kwargs["Message"]["Body"]["Text"]["Data"] == "plain hello"


def test_message_structure_sent_to_ses(boto_manager):
    bm, _ = boto_manager
    ses_client = bm.ses_client
    ses_client.send_email.return_value = {"MessageId": "abc123"}

    bm.send_email(
        SENDER="a@example.com", RECIPIENT="b@example.com", SUBJECT="Test Subject",
        BODY_HTML="<p>hello</p>", BODY_TEXT="hello",
    )

    _, kwargs = ses_client.send_email.call_args
    assert kwargs["Source"] == "a@example.com"
    assert kwargs["Message"]["Subject"]["Data"] == "Test Subject"
    assert kwargs["Message"]["Body"]["Html"]["Data"] == "<p>hello</p>"
    assert kwargs["Message"]["Body"]["Html"]["Charset"] == "UTF-8"

def test_client_error_raises_internal_error(boto_manager):
    bm, _ = boto_manager
    ses_client = bm.ses_client
    ses_client.send_email.side_effect = make_client_error("Email address not verified")

    with pytest.raises(InternalError, match="Email address not verified"):
        bm.send_email(
            SENDER="a@example.com", RECIPIENT="b@example.com", SUBJECT="Hi",
            BODY_HTML="<p>hi</p>",
        )


def test_successful_send_does_not_raise(boto_manager):
    bm, _ = boto_manager
    ses_client = bm.ses_client
    ses_client.send_email.return_value = {"MessageId": "abc123"}

    # should complete without raising
    bm.send_email(
        SENDER="a@example.com", RECIPIENT="b@example.com", SUBJECT="Hi",
        BODY_HTML="<p>hi</p>",
    )
